import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AccentColorStyleInjector } from './Color'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <AccentColorStyleInjector />
      </head>
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col p-24">
          <p className="text-center">Color</p>
          {children}
        </main>
      </body>
    </html>
  )
}
